# Vagrant VM configuration
# for testing with actual ALSA kernel

$script = <<-'SCRIPT'
  sudo apt update
  sudo apt install -y python3-cffi python3-venv python3-pip libffi-dev libasound-dev alsa-utils
  export PATH="$PATH:$HOME/.local/bin"
  pip3 install tox
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian10"

    config.vm.define 'vm'

    config.vm.synced_folder ".", "/vagrant"

    config.vm.provision "shell", inline: $script
end
