
name: CI


on:
  push:
    branches: [ "main" ]
    tags: [ "v0.*", "v1.*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}


jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install isort==5.13.2 flake8==7.0.0

    - name: Check coding style (flake8)
      run: "flake8 alsa_midi tests"

    - name: Check imports sorting (isort)
      run: "isort --check --dont-follow-links alsa_midi tests"

  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
        sudo apt update
        sudo apt install -y libasound2-dev

    - name: Run tests
      run: "tox -e py -- -vv"

  test-on-alsa-kernel:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Multipass
      run: |
        sudo snap install multipass --classic
        sudo snap wait system seed.loaded
        sleep 5

    - name: Start Multipass VM
      run: |
        sudo multipass launch 24.04 -n test-vm
        sleep 10

    - name: Run tests in Multipass VM
      run: |
        set -x
        sudo multipass exec test-vm -- sudo modprobe snd-seq-device
        sudo multipass exec test-vm -- sudo modprobe snd-seq-dummy
        sudo multipass exec test-vm -- sudo modprobe snd-rawmidi
        sudo multipass exec test-vm -- sudo sh -c 'chmod a+rw /dev/snd/*'
        sudo multipass transfer --recursive $PWD test-vm:/home/ubuntu/code
        sudo multipass exec test-vm -- sudo apt install -y python3-cffi python3-venv python3-pip python3-wheel python3-venv libffi-dev libasound-dev alsa-utils
        curl -LsSf https://astral.sh/uv/install.sh | sudo multipass exec test-vm -- sh
        sudo multipass exec test-vm -- bash -c '. $HOME/.local/bin/env && cd code && uvx tox -e py -- -vv'

    - name: Stop and delete VM
      run: |
        sudo multipass stop test-vm
        sudo multipass delete test-vm
        sudo multipass purge

  build-pure:

    needs:
      - test
      - test-on-alsa-kernel

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine
        sudo apt update

    - name: Build
      run: |
        export PY_ALSA_MIDI_NO_COMPILE=1
        python -m build .
        twine check dist/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: dist-pure
        path: dist

  # separate jobs, as matrix does not work with 'uses: docker://' and 'container:' does not work well with 'actions/checkout'

  build-manylinux_2_12_x86_64:

    needs:
      - test
      - test-on-alsa-kernel

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build and test ${{ matrix.manylinux-tag }} wheels
      uses: docker://quay.io/pypa/manylinux2010_x86_64
      with:
        args: ./build-wheels.sh manylinux_2_12_x86_64

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: wheelhouse-manylinux_2_12_x86_64
        path: wheelhouse

  build-manylinux_2_12_i686:

    needs:
      - test
      - test-on-alsa-kernel

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build and test ${{ matrix.manylinux-tag }} wheels
      uses: docker://quay.io/pypa/manylinux2010_i686
      with:
        args: linux32 ./build-wheels.sh manylinux_2_12_i686

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: wheelhouse-manylinux_2_12_i686
        path: wheelhouse

  build-manylinux_2_17_x86_64:

    needs:
      - test
      - test-on-alsa-kernel

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build and test ${{ matrix.manylinux-tag }} wheels
      uses: docker://quay.io/pypa/manylinux2014_x86_64
      with:
        args: ./build-wheels.sh manylinux_2_17_x86_64

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: wheelhouse-manylinux_2_17_x86_64
        path: wheelhouse

  build-manylinux_2_17_i686:

    needs:
      - test
      - test-on-alsa-kernel

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build and test ${{ matrix.manylinux-tag }} wheels
      uses: docker://quay.io/pypa/manylinux2014_i686
      with:
        args: linux32 ./build-wheels.sh manylinux_2_17_i686

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: wheelhouse-manylinux_2_17_i686
        path: wheelhouse

  build-manylinux_2_28_x86_64:

    needs:
      - test
      - test-on-alsa-kernel

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build and test ${{ matrix.manylinux-tag }} wheels
      uses: docker://quay.io/pypa/manylinux_2_28_x86_64
      with:
        args: ./build-wheels.sh manylinux_2_28_x86_64

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: wheelhouse-manylinux_2_28_x86_64
        path: wheelhouse

  publish:

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    environment:
      name: pypi
      url: https://pypi.org/p/alsa-midi

    permissions:
      id-token: write

    needs:
      - build-pure
      - build-manylinux_2_12_x86_64
      - build-manylinux_2_12_i686
      - build-manylinux_2_17_x86_64
      - build-manylinux_2_17_i686
      - build-manylinux_2_28_x86_64

    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7

      - name: Collect dist files
        run: |
          ls -lR .
          mkdir -p dist
          mv wheelhouse-*/*manylinux*.whl dist/
          mv dist-pure/*-py3-none-any.whl dist/
          mv dist-pure/*.tar.gz dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
